baseURL = 'https://codeweng.com/'
languageCode = 'en-us'
title = 'CodeWeng Blog'
theme = 'awesome'
hasCJKLanguage = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/yymcct"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/yymcct"

[params]
  goToTop = true
  description = "CodeWeng Blog"

[[menus.main]]
name = '首页'
pageRef = '/'
url = '/'
weight = 10

[[menus.main]]
name = '文章'
pageRef = '/posts/'
url = '/posts/'
weight = 20

[[menus.main]]
name = '关于'
pageRef = '/about/'
url = '/about/'
weight = 40

[params.author]
name = "CodeWeng"
avatar = "avatar.jpg"
intro = "CodeWeng — Builder & Explorer"
description = "Software Engineer · Lifelong Learner"